### ISSUE TITLE
Show the grid gutter

### ISSUE THREAD

**Issue by janstieler** [alefeuvre/foundation-grid-displayer#8]
Hi,
it would great if I it would be possible to show also the gutter of the grid.
In my situation its Bootstrap 3.

Greets

**Comment by ryandeussing** [comment]
+1

**Comment by alefeuvre** [comment]
Thank you Jan for submitting this issue.
Since B3 now uses border-box sizing for the gutters, I would have to colour left and right padding for the gutters to show. There should be a way to [do this with an overlay of some sort](http://stackoverflow.com/questions/14628601/can-i-add-background-color-only-for-padding), but I'm afraid I haven't much time to look into this.
I'll keep you posted here though, as soon as I can work on this.
Do not hesitate to submit a pull request if you find a solution.

**Comment by JayVerb** [comment]
I added a border-right and border-left width of 10px set to a different color. Doing this, you can also remove the option to hide every other column making it easier to follow the grid pattern. Works great, but only for Bootstrap 3 selection.

**Comment by ryandeussing** [comment]
@JayVerb I don't see that code in your fork, could you push it? Thanks

**Comment by JayVerb** [comment]
Sorry, didn't commit it, made changes for local project. I push it soon.

**Comment by alefeuvre** [comment]
@JayVerb Hi Jay, looking forward to your pull request to give your proposal a try. You have me curious as I'm wondering how adding 10px-wide borders on both sides would help visualising the gutter.

**Comment by JayVerb** [comment]
I have submitted a pull request. Sorry it is a mess, wasn't planning to really contribute, just making changes while I was working on a project. No minified versions were created. Would love to see if these changes are beneficial.

**Comment by alefeuvre** [comment]
[Version 3.0](https://github.com/alefeuvre/foundation-grid-displayer/blob/gh-pages/CHANGELOG.md#version-30---february-8-2014) of the grid displayer is out. It now shows the "gutters" (i.e. column padding) for gutterless grid systems, that is Bootstrap 3, Foundation 4 & 5. Many thanks to Jay for its PR!
